name: Verify Azure Storage Access
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_DBSERVER: ${{ secrets.AZURE_DBSERVERNAME }}  # Krótka nazwa (np. 'mlopsserverdemo')
  AZURE_DBNAME: ${{ secrets.AZURE_DBNAME }}
  AZURE_DBUSERNAME: ${{ secrets.AZURE_DBUSERNAME }}
  AZURE_DBUSERPASS: ${{ secrets.AZURE_DBUSERPASS }}
  AZURE_DBRESOURCEGROUP: ${{ secrets.AZURE_DBRESOURCEGROUP }}
  AZURE_DBCLIENT_ID: ${{ secrets.AZURE_CLIENT_DEV_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  verify-storage:
    runs-on: ubuntu-22.04
    steps:

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Test Storage Access
        run: |
          # Weryfikacja konta storage
          az storage account show \
            --name ${{ env.AZURE_STORAGE_ACCOUNT }} \
            --query 'id'

          # Lista kontenerów
          az storage container list \
            --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
            --auth-mode login

          # Próba utworzenia testowego pliku
          echo "Test file" > test.txt
          
          # Upload do kontenera
          az storage blob upload \
            --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
            --container-name ${{ env.AZURE_STORAGE_CONTAINER }} \
            --name test-file.txt \
            --file test.txt \
            --auth-mode login

          # Czyszczenie
          rm test.txt

      - name: Verify Database Connection (optional)
        if: env.AZURE_DBSERVER
        run: |
          # Przykładowe połączenie z bazą danych
          psql "host=${{ env.AZURE_DBSERVER }} \
                port=${{ env.AZURE_DBPORT }} \
                dbname=${{ env.AZURE_DBNAME }} \
                user=${{ env.AZURE_DBUSERNAME }} \
                password=${{ secrets.AZURE_DBUSERPASS }}" \
          -c "SELECT 1;"
