name: Verify Azure Storage Access
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_STORAGE_RESOURCEGROUP }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_STORAGE_ACCOUNT: ${{secrets.AZURE_STORAGE_ACCOUNT }}
  AZURE_STORAGE_CONTAINER: ${{secrets.AZURE_STORAGE_CONTAINER }}

jobs:
  verify-storage:
    runs-on: ubuntu-22.04
    steps:

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Test Storage Access
        run: |
          # Weryfikacja konta storage
          az storage account show \
            --name ${{ env.AZURE_STORAGE_ACCOUNT }} \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --query 'id'

          # Lista kontenerów
          az storage container list \
            --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
            --auth-mode login

          # Próba utworzenia testowego pliku
          echo "Test file" > test.txt
          
          # Upload do kontenera
          az storage blob upload \
            --account-name ${{ env.AZURE_STORAGE_ACCOUNT }} \
            --container-name ${{ env.AZURE_STORAGE_CONTAINER }} \
            --name test-file.txt \
            --file test.txt \
            --auth-mode login

          # Czyszczenie
          rm test.txt
