name: Azure DB Access Validation
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_DBSERVER: ${{ secrets.AZURE_DBSERVER }}
  AZURE_DBRESOURCEGROUP: ${{ secrets.AZURE_DBRESOURCEGROUP }}
  AZURE_DBCLIENT_ID: ${{ secrets.AZURE_CLIENT_DEV_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  validate-db-access:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_DBCLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Verify SQL Server Exists  # Renamed for clarity
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az sql server show --name mlopsserverdemo.database.windows.net --resource-group DEMO_AUG_DEV

      - name: List SQL Databases
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az sql db list --server ${{ env.AZURE_DBSERVER }} --resource-group ${{ env.AZURE_DBRESOURCEGROUP }}
