name: Azure DB Access Validation

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_DBSERVER: ${{ secrets.AZURE_DBSERVER }}        # Should be short name (e.g., 'mlopsserverdemo')
  AZURE_DBSERVERNAME: ${{ secrets.AZURE_DBSERVERNAME }}
  AZURE_DBNAME: ${{ secrets.AZURE_DBNAME }}            # Fixed secret reference
  AZURE_DBRESOURCEGROUP: ${{ secrets.AZURE_DBRESOURCEGROUP }}
  AZURE_DBCLIENT_ID: ${{ secrets.AZURE_CLIENT_DEV_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  validate-db-access:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_DBCLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Install sqlcmd
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc

      - name: Verify SQL Server Exists
        uses: azure/cli@v2
        with:
          inlineScript: |
            az sql server show \
              --name ${{ env.AZURE_DBSERVERNAME }} \
              --resource-group ${{ env.AZURE_DBRESOURCEGROUP }}

      - name: List SQL Databases
        uses: azure/cli@v2
        with:
          inlineScript: |
            az sql db list \
              --server ${{ env.AZURE_DBSERVERNAME }} \
              --resource-group ${{ env.AZURE_DBRESOURCEGROUP }}

      - name: Connect to SQL Database
        run: |
          sqlcmd -S "${{ env.AZURE_DBSERVERNAME }}.database.windows.net" \
            -d "${{ env.AZURE_DBNAME }}" \
            -G \
            -U "ClientId=${{ env.AZURE_DBCLIENT_ID }}" \
            -Q "SELECT CURRENT_USER;"
