name: Azure DB Access Validation

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_DBSERVERNAME: ${{ secrets.AZURE_DBSERVERNAME }}  # Krótka nazwa (np. 'mlopsserverdemo')
  AZURE_DBSERVER: ${{ secrets.AZURE_DBSERVER }} 
  AZURE_DBNAME: ${{ secrets.AZURE_DBNAME }}
  AZURE_DBUSERNAME: ${{ secrets.AZURE_DBUSERNAME }}
  AZURE_DBUSERPASS: ${{ secrets.AZURE_DBUSERPASS }}
  AZURE_DBRESOURCEGROUP: ${{ secrets.AZURE_DBRESOURCEGROUP }}
  AZURE_DBCLIENT_ID: ${{ secrets.AZURE_CLIENT_DEV_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  validate-db-access:
    runs-on: ubuntu-22.04  # Wymagany dla działających repozytoriów Microsoft
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_DBCLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Install sqlcmd and ODBC driver
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18
          echo "/opt/mssql-tools18/bin" >> $GITHUB_PATH

      - name: Verify SQL Server Exists
        uses: azure/cli@v2
        with:
          inlineScript: |
            az sql server show \
              --name ${{ env.AZURE_DBSERVERNAME }} \
              --resource-group ${{ env.AZURE_DBRESOURCEGROUP }}

      - name: List SQL Databases
        uses: azure/cli@v2
        with:
          inlineScript: |
            az sql db list \
              --server ${{ env.AZURE_DBSERVERNAME }} \
              --resource-group ${{ env.AZURE_DBRESOURCEGROUP }}

      - name: Connect to SQL Database with Managed Identity
        run: |
          sqlcmd -S "${{ env.AZURE_DBSERVERNAME }}.database.windows.net" \
            -d "${{ env.AZURE_DBNAME }}" \
            -U "${{ env.AZURE_DBUSERNAME }}" \
            -P "${{ env.AZURE_DBUSERPASS }}" \
            -Q "SELECT CURRENT_USER;"
