name: Azure DB Access Validation

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZURE_DBSERVER: ${{ secrets.AZURE_DBSERVER}}
  AZURE_DBRESOURCEGROUP: ${{ secrets.AZURE_DBRESOURCEGROUP }}
  AZURE_DBCLIENTID: ${{ secrets.AZURE_CLIENT_DEV_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  validate-db-access:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: $AZURE_DBCLIENTID
          tenant-id: $AZURE_TENANT_ID
          subscription-id: $AZURE_SUBSCRIPTION_ID

      - name: Test Azure SQL Connection
        run: az sql db list --server $AZURE_DBSERVER --resource-group $AZURE_DBRESOURCEGROUP

