name: Predict on new data or with new model

on: 
  push:
    branches:
      - main
    paths:
      - 'data/raw/test_cholesterol.xlsx'
      - 'data/processed/test_cholesterol.xlsx'
      - 'ARISA_DSML/predict.py'
      - 'models/catboost_model_cholesterol.cbm'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install kaggle pandas  # Add required packages

      - name: Configure Kaggle credentials
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          mkdir -p ~/.kaggle
          echo '{"username":"$KAGGLE_USERNAME","key":"$KAGGLE_KEY"}' > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          echo "KAGGLE_CONFIG_DIR=~/.kaggle" >> $GITHUB_ENV

      - name: Download dataset
        run: |
          kaggle datasets download -d joannborkowska/cholesterol-supplementation-classification -p data/raw/
          unzip data/raw/*.zip -d data/raw/

      - name: Run preprocessing
        run: python -m ARISA_DSML.preproc
